import type { LearnerState } from "./learnerTypes";

export const initialLearnerState: LearnerState = {
  phase: "welcome",
  currentConcept: "parameters",
  concepts: {
    parameters: {
      id: "parameters",
      mastery: 0,
      attempts: 0,
      correctAttempts: 0,
      incorrectAttempts: 0,
      recentOutcome: null,
    },
    returnValues: {
      id: "returnValues",
      mastery: 0,
      attempts: 0,
      correctAttempts: 0,
      incorrectAttempts: 0,
      recentOutcome: null,
    },
    functionCalls: {
      id: "functionCalls",
      mastery: 0,
      attempts: 0,
      correctAttempts: 0,
      incorrectAttempts: 0,
      recentOutcome: null,
    },
  },
  attempts: [],
  consecutiveFailures: 0,
  recovery: {
    triggered: false,
    triggerReason: null,
    diagnosisStatus: "idle",
    misconception: null,
    recommendedMode: null,
    selectedMode: null,
    contentStatus: "idle",
    recovered: null,
  },
  mission: {
    attempted: false,
    submission: "",
    evaluationStatus: "idle",
    passed: null,
    hintUsed: false,
    feedback: null,
    weakness: null,
  },
  nextAction: null,
  accessibility: {
    largeText: false,
    highContrast: false,
    reducedMotion: false,
    enhancedFocus: false,
  },
};
