import type { LearnerState } from "./learnerTypes";

export const initialLearnerState: LearnerState = {
  phase: "welcome",
  currentConcept: "",
  concepts: {},
  attempts: [],
  consecutiveFailures: 0,
  recovery: {
    triggered: false,
    triggerReason: null,
    diagnosisStatus: "idle",
    misconception: null,
    recommendedMode: null,
    selectedMode: null,
    contentStatus: "idle",
    recovered: null,
    recoveryContent: null,
  },
  mission: {
    attempted: false,
    submission: "",
    evaluationStatus: "idle",
    passed: null,
    hintUsed: false,
    feedback: null,
    weakness: null,
  },
  nextAction: null,
  accessibility: {
    largeText: false,
    highContrast: false,
    reducedMotion: false,
    enhancedFocus: false,
  },
  lesson: null,
  lessonStatus: "idle",
  topicInput: "",
  learningDurationMinutes: null,
  initialLearningMode: null,
};
